import { View, Text } from 'react-native'

export default function SurvivalScreen() {
  return (
<<<<<<< HEAD
    <SafeAreaView style={styles.safeArea} edges={["top"]}>
      <View style={styles.root}>
        {/* HEADER */}
        <LinearGradient colors={[ROSE_600, PINK_700]} style={styles.header}>
          <View style={styles.headerRow}>
            <View>
              <Text style={styles.headerTitle}>
                {t("survival.title") || "Survival Kit"}
              </Text>
              <Text style={styles.headerSub}>Bali Safety & Tools</Text>
            </View>
            <ShieldAlert size={30} color="white" />
          </View>
        </LinearGradient>

        {/* Tabs */}
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          style={styles.tabsContainer}
          contentContainerStyle={styles.tabsContent}
        >
          {TABS.map((tab) => (
            <TouchableOpacity
              key={tab.id}
              style={[styles.tab, activeTab === tab.id && styles.tabActive]}
              onPress={() => setActiveTab(tab.id)}
            >
              <tab.icon
                size={18}
                color={activeTab === tab.id ? "#FFFFFF" : GRAY_600}
              />
              <Text
                style={[
                  styles.tabText,
                  activeTab === tab.id && styles.tabTextActive,
                ]}
              >
                {tab.label}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {/* Content */}
        <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          {renderSection()}
        </ScrollView>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: BG },
  root: { flex: 1 },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { fontSize: 28, fontWeight: "800", color: WHITE },
  headerSub: { fontSize: 14, color: "rgba(255,255,255,0.8)", marginTop: 4 },
  tabsContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_200,
    zIndex: 999,
  },
  tabsContent: { gap: 8, flexGrow: 0 },
  tab: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: GRAY_200,
    gap: 6,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.08)",
    elevation: 2,
    width: 95,
    minWidth: 95,
    maxWidth: 95,
    flexShrink: 0,
    justifyContent: 'center',
  },
  tabActive: { backgroundColor: ROSE_600, borderColor: ROSE_600 },
  tabText: { fontSize: 13, fontWeight: "600", color: GRAY_600 },
  tabTextActive: { color: WHITE },
  scrollContent: { padding: 16, paddingBottom: 100 },
  card: {
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  cardTitle: { fontSize: 17, fontWeight: "700", color: GRAY_800, flex: 1 },
  editText: { fontSize: 13, color: ROSE_600, fontWeight: "600" },
  converterSection: { gap: 12 },
  converterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  converterInput: { flex: 1, alignItems: "center" },
  converterLabel: { fontSize: 12, color: GRAY_500, marginBottom: 4 },
  converterInputText: {
    fontSize: 24,
    fontWeight: "800",
    color: GRAY_800,
    textAlign: "center",
  },
  converterResultText: {
    fontSize: 24,
    fontWeight: "800",
    color: GREEN_500,
    textAlign: "center",
  },
  reverseBtn: {
    padding: 10,
    backgroundColor: GRAY_100,
    borderRadius: 50,
    marginHorizontal: 12,
  },
  rateInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: GRAY_200,
  },
  rateInfoText: { fontSize: 13, color: GRAY_500 },
  visaLoading: { alignItems: "center", paddingVertical: 20 },
  visaContent: { gap: 16 },
  visaMainRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  visaDaysContainer: { alignItems: "center" },
  visaDaysText: { fontSize: 56, fontWeight: "900" },
  visaDaysLabel: { fontSize: 14, color: GRAY_500, fontWeight: "600" },
  visaStatusBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: GRAY_100,
  },
  visaStatusText: { fontSize: 14, fontWeight: "700" },
  visaDetails: { gap: 8 },
  visaDetailRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  visaDetailText: { fontSize: 14, color: GRAY_600 },
  visaWarning: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(239,68,68,0.1)",
    padding: 12,
    borderRadius: 12,
  },
  visaWarningText: { fontSize: 13, color: RED_500, fontWeight: "600", flex: 1 },
  bentoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  bentoTile: {
    width: "47%",
    height: 60,
    borderRadius: 14,
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 4,
    padding: 10,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.12)",
    elevation: 4,
    flexShrink: 0,
    backgroundColor: "rgba(255, 255, 255, 0.80)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.40)",
  },
  bentoIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  bentoTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: GRAY_800,
  },
  bentoNumber: { fontSize: 16, fontWeight: "800" },
  volcanoCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(249, 115, 22, 0.3)",
  },
  volcanoHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  volcanoTitle: { fontSize: 16, fontWeight: "700", color: GRAY_800 },
  volcanoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: GRAY_100,
  },
  volcanoInfo: { flex: 1 },
  volcanoName: { fontSize: 14, fontWeight: "600", color: GRAY_800 },
  volcanoDistance: { fontSize: 12, color: GRAY_500 },
  volcanoStatus: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  volcanoStatusText: { fontSize: 11, fontWeight: "700" },
  magmaButton: {
    flexDirection: "row",
    backgroundColor: ORANGE_500,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
  },
  magmaButtonText: { fontSize: 14, fontWeight: "700", color: WHITE },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  loadingText: { fontSize: 15, color: GRAY_500, marginTop: 12 },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  errorText: { fontSize: 15, color: GRAY_500, marginTop: 12 },
  weatherCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  weatherMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  weatherIcon: { fontSize: 48 },
  weatherTemp: { flex: 1 },
  temperature: { fontSize: 42, fontWeight: "800", color: GRAY_800 },
  condition: { fontSize: 16, color: GRAY_500 },
  weatherDetails: { flexDirection: "row", justifyContent: "space-around" },
  weatherDetail: { alignItems: "center", gap: 4 },
  weatherDetailLabel: { fontSize: 12, color: GRAY_500 },
  weatherDetailValue: { fontSize: 14, fontWeight: "700", color: GRAY_800 },
  weatherAlerts: {
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    borderRadius: 12,
    padding: 12,
  },
  alertTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 8,
  },
  alertItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  alertText: { fontSize: 13, color: GRAY_500, flex: 1 },
  infoCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 6,
  },
  infoText: { fontSize: 13, color: GRAY_500, lineHeight: 18 },
  symptomsCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  symptomsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 8,
  },
  symptomList: { gap: 4 },
  symptom: { fontSize: 13, color: GRAY_600 },
  treatmentCard: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  treatmentTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 8,
  },
  treatmentList: { gap: 4 },
  treatment: { fontSize: 13, color: GRAY_600 },
  warningCard: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
  },
  warningTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: RED_500,
    marginTop: 8,
    textAlign: "center",
  },
  warningText: {
    fontSize: 13,
    color: GRAY_500,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  firstAidCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  firstAidTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 12,
  },
  stepList: { gap: 10 },
  step: { flexDirection: "row", gap: 12 },
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: RED_500,
    justifyContent: "center",
    alignItems: "center",
  },
  stepNumberText: { fontSize: 13, fontWeight: "700", color: WHITE },
  stepText: { fontSize: 13, color: GRAY_600, flex: 1, lineHeight: 18 },
  clinicsCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  clinicsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 12,
  },
  rabiesClinicItem: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: GRAY_200,
  },
  rabiesClinicInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  rabiesClinicName: { fontSize: 14, fontWeight: "600", color: GRAY_800 },
  rabiesClinicPhone: {
    fontSize: 13,
    color: GREEN_500,
    fontWeight: "600",
    marginBottom: 8,
  },
  rabiesClinicActions: { flexDirection: "row", gap: 8 },
  callButtonSmall: {
    flexDirection: "row",
    backgroundColor: GREEN_500,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: "center",
    gap: 6,
  },
  callButtonText: { fontSize: 12, fontWeight: "600", color: WHITE },
  mapsButtonSmall: {
    flexDirection: "row",
    backgroundColor: "#00B4D8",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: "center",
    gap: 6,
  },
  mapsButtonText: { fontSize: 12, fontWeight: "600", color: WHITE },
  emergencyCallButton: {
    flexDirection: "row",
    backgroundColor: RED_500,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  emergencyCallText: { fontSize: 16, fontWeight: "800", color: WHITE },
  methanolWarningCard: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
  },
  methanolWarningTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: RED_500,
    marginTop: 8,
    textAlign: "center",
  },
  methanolWarningText: {
    fontSize: 13,
    color: GRAY_500,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  methanolSymptomsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 8,
  },
  methanolSymptomList: { gap: 6 },
  methanolSymptom: { fontSize: 13, color: GRAY_600 },
  safeBarsCard: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  safeBarsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 10,
  },
  safeBarItem: {
    backgroundColor: WHITE,
    borderRadius: 10,
    padding: 10,
    marginBottom: 6,
  },
  safeBarInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  safeBarName: { fontSize: 14, fontWeight: "600", color: GRAY_800 },
  safeBarAddress: { fontSize: 12, color: GRAY_500, marginBottom: 2 },
  safeBarNotes: { fontSize: 11, color: GREEN_500 },
  tipsCard: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderRadius: 12,
    padding: 14,
  },
  tipsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 6,
  },
  tipsText: { fontSize: 13, color: GRAY_600, lineHeight: 20 },
  // === Scanner Styles ===
  scannerAllergenSection: { marginBottom: 20 },
  scannerSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: GRAY_800,
    marginBottom: 12,
  },
  scannerAllergenChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  scannerAllergenChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    gap: 6,
  },
  scannerAllergenIcon: { fontSize: 16 },
  scannerAllergenText: { fontSize: 13 },
  scannerCameraSection: { marginBottom: 20 },
  scannerCameraContainer: {
    height: 280,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  scannerCameraText: { fontSize: 14, marginTop: 12, textAlign: "center" },
  scannerPermissionButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
  },
  scannerPermissionButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  scannerCameraWrapper: {
    height: 280,
    borderRadius: 24,
    overflow: "hidden",
    position: "relative",
  },
  scannerCamera: { flex: 1 },
  scannerCameraOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  scannerScanFrame: { width: 220, height: 220, position: "relative" },
  scannerCornerTopLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 40,
    height: 40,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderColor: "#FFFFFF",
    borderTopLeftRadius: 12,
  },
  scannerCornerTopRight: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 40,
    height: 40,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderColor: "#FFFFFF",
    borderTopRightRadius: 12,
  },
  scannerCornerBottomLeft: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 40,
    height: 40,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderColor: "#FFFFFF",
    borderBottomLeftRadius: 12,
  },
  scannerCornerBottomRight: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 40,
    height: 40,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderColor: "#FFFFFF",
    borderBottomRightRadius: 12,
  },
  scannerScanGuideText: {
    color: "#FFFFFF",
    fontSize: 14,
    marginTop: 16,
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  scannerScanButton: {
    position: "absolute",
    bottom: 16,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 28,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
  },
  scannerScanButtonDisabled: { opacity: 0.7 },
  scannerScanButtonText: { color: ROSE_600, fontSize: 14, fontWeight: "600" },
  scannerInfoCard: { borderRadius: 20, padding: 16, marginBottom: 20 },
  scannerInfoCardContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  scannerInfoCardText: { flex: 1 },
  scannerInfoCardTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: GRAY_800,
    marginBottom: 4,
  },
  scannerInfoCardDescription: { fontSize: 13, color: GRAY_500, lineHeight: 18 },
  scannerResultsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  scannerResultsTitle: { fontSize: 18, fontWeight: "700", color: GRAY_800 },
  scannerResetButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  scannerResetButtonText: { fontSize: 13, fontWeight: "600" },
  scannerSummaryCard: { borderRadius: 20, padding: 16, marginBottom: 16 },
  scannerSummaryStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  scannerSummaryStat: { alignItems: "center" },
  scannerSummaryStatDivider: { width: 1, height: 40 },
  scannerSummaryStatValue: { fontSize: 28, fontWeight: "800" },
  scannerSummaryStatLabel: { fontSize: 12, marginTop: 4 },
  scannerMenuItemCard: {
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
  },
  scannerMenuItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  scannerMenuItemInfo: { flex: 1, marginRight: 12 },
  scannerMenuItemMeta: { alignItems: "flex-end" },
  scannerMenuItemName: { fontSize: 16, fontWeight: "600" },
  scannerMenuItemDescription: { fontSize: 13, marginTop: 4 },
  scannerMenuItemPrice: { fontSize: 16, fontWeight: "700" },
  scannerSafetyBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    marginTop: 8,
    gap: 4,
  },
  scannerSafetyBadgeText: { fontSize: 11, fontWeight: "600" },
  scannerAllergenTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 12,
  },
  scannerAllergenTag: {
    backgroundColor: "rgba(239,68,68,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  scannerAllergenTagText: { fontSize: 11, color: "#EF4444", fontWeight: "600" },
  // === Dictionary Styles ===
  dictSearchBar: {
    zIndex: 10,
    position: 'relative',
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE,
    borderRadius: 12,
    paddingHorizontal: 12,
    gap: 8,
    marginBottom: 12,
    marginHorizontal: 0,
  },
  dictSearchInput: {
    flex: 1,
    fontSize: 16,
    color: GRAY_800,
    paddingVertical: 12,
  },
  dictCategoriesScroll: { marginBottom: 12 },
  dictCategoriesContent: { gap: 8 },
  dictCategoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: WHITE,
    borderWidth: 1,
    borderColor: GRAY_200,
  },
  dictCategoryChipText: { fontSize: 14, color: GRAY_500, fontWeight: "600" },
  dictResultsCount: { fontSize: 14, color: GRAY_500, marginBottom: 8 },
  dictEntryCard: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  dictEntryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  dictEntryMain: { flex: 1 },
  dictEntryIndonesian: {
    fontSize: 18,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 4,
  },
  dictEntryPronunciation: {
    fontSize: 14,
    color: GRAY_500,
    fontStyle: "italic",
  },
  dictCopyButton: { padding: 4 },
  dictEntryTranslation: { marginBottom: 8 },
  dictEntryGerman: {
    fontSize: 16,
    color: GREEN_500,
    fontWeight: "600",
    marginBottom: 2,
  },
  dictEntryEnglish: { fontSize: 14, color: GRAY_500 },
  dictCategoryBadge: {
    fontSize: 12,
    color: GRAY_500,
    backgroundColor: GRAY_100,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  dictExamplesSection: {
    borderTopWidth: 1,
    borderTopColor: GRAY_200,
    paddingTop: 12,
  },
  dictExamplesTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: GRAY_500,
    marginBottom: 8,
  },
  dictExample: { marginBottom: 8 },
  dictExampleIndonesian: { fontSize: 14, color: GRAY_800, marginBottom: 2 },
  dictExampleGerman: { fontSize: 14, color: GRAY_500 },
  dictEmptyState: { alignItems: "center", paddingVertical: 60 },
  dictEmptyText: { fontSize: 16, color: GRAY_500, marginTop: 12 },
  dictSectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: GRAY_800,
    marginBottom: 12,
  },
  // === Law Hub Styles ===
  lawIntroSection: {
    alignItems: "center",
    paddingVertical: 24,
    marginBottom: 16,
  },
  lawIntroTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: GRAY_800,
    marginTop: 12,
    marginBottom: 8,
  },
  lawIntroText: {
    fontSize: 14,
    color: GRAY_500,
    textAlign: "center",
    lineHeight: 20,
  },
  lawCategoryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderLeftWidth: 4,
  },
  lawCategoryIcon: { fontSize: 32, marginRight: 12 },
  lawCategoryInfo: { flex: 1 },
  lawCategoryTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: GRAY_800,
    marginBottom: 4,
  },
  lawCategoryCount: { fontSize: 12, color: GRAY_500 },
  lawCategoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 8,
  },
  lawCategoryHeaderIcon: { fontSize: 32 },
  lawCategoryHeaderTitle: { fontSize: 20, fontWeight: "700", color: GRAY_800 },
  lawCard: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
  },
  lawHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  lawTitleSection: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  lawTitle: { fontSize: 16, fontWeight: "600", color: GRAY_800, flex: 1 },
  lawSeverityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  lawSeverityBadgeText: { fontSize: 10, fontWeight: "700", color: WHITE },
  lawDescription: { fontSize: 14, color: GRAY_500, lineHeight: 20 },
  lawBackButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 16,
  },
  lawBackText: { fontSize: 14, color: ROSE_600, fontWeight: "600" },
  lawSeverityText: { fontSize: 14, fontWeight: "700" },
  lawDetailCard: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  lawDetailLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: GRAY_500,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  lawDetailText: { fontSize: 14, color: GRAY_800, lineHeight: 22 },
  lawPenaltyCard: {
    backgroundColor: "rgba(239,68,68,0.05)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.2)",
  },
  lawPenaltyText: { color: RED_500, fontWeight: "600" },
  lawTip: { flexDirection: "row", gap: 8, marginBottom: 8 },
  lawTipBullet: { fontSize: 14, color: GREEN_500 },
  lawTipText: { flex: 1, fontSize: 14, color: GRAY_800, lineHeight: 22 },
  lawDisclaimer: {
    backgroundColor: "rgba(245,158,11,0.1)",
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  lawDisclaimerText: {
    fontSize: 12,
    color: "rgba(146,64,14,1)",
    lineHeight: 18,
    fontStyle: "italic",
  },
});
=======
    <View className="flex-1 items-center justify-center bg-background">
      <Text className="text-xl font-bold">Survival Screen</Text>
    </View>
  )
}
>>>>>>> 0a14abbe21b23896b6404d339fce90b762ddbc31
